theme: jekyll-theme-minimal
title: The Informed Voter Project
logo: /images/logo-bw.png
show_downloads: True
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
